### ISSUE TITLE
question about 'time since last report'

### ISSUE THREAD

**Issue by funkychameleon** [akira-trinity/leagueReap3r#1]
Hello, great app. I extracted, ran it, and set my league path to Local Disk>Riot Games>League of Legends. I reported but the 'time since last report' says 46 days. Is this a bug or am I doing something wrong? Thanks.

**Comment by 0adri3n** [comment]
Hi ! It's normal cuz it's the date of the original config file, I didn't change it mb

**Comment by funkychameleon** [comment]
Ah okay. Thanks!
